// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.context;

#nullable disable

namespace saccoshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718053435_gh")]
    partial class gh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RoomOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomName = "Lati Technologies",
                            RoomOwner = "Martin Lubega"
                        },
                        new
                        {
                            RoomId = 2,
                            RoomName = "DreamLand",
                            RoomOwner = "Isaac"
                        },
                        new
                        {
                            RoomId = 3,
                            RoomName = "Pete Games",
                            RoomOwner = "Leonard"
                        });
                });

            modelBuilder.Entity("Entities.Models.ShopItem", b =>
                {
                    b.Property<int>("ShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShopItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopItemId"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("ShopItemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShopItemName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ShopItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            ShopItemId = 1,
                            RoomId = 1,
                            ShopItemDescription = "Lenovo T430 i7 series with a built-in battery pack ",
                            ShopItemName = "Lenovo Think Pad "
                        },
                        new
                        {
                            ShopItemId = 2,
                            RoomId = 2,
                            ShopItemDescription = "A high resolution camera with backup battery ",
                            ShopItemName = "GL360 Camera"
                        },
                        new
                        {
                            ShopItemId = 3,
                            RoomId = 3,
                            ShopItemDescription = "This brand new console belongs the the XRNM model series with NVDIA accerelators",
                            ShopItemName = "XBox Game Console"
                        },
                        new
                        {
                            ShopItemId = 4,
                            RoomId = 1,
                            ShopItemDescription = "i7 server with 64TB RAM provision and upto 200TB storage capacity.Comes with a built-in DHCP multi-port router",
                            ShopItemName = "RTC293 HP Server "
                        });
                });

            modelBuilder.Entity("Entities.Models.ShopItem", b =>
                {
                    b.HasOne("Entities.Models.Room", "Room")
                        .WithMany("ShopItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entities.Models.Room", b =>
                {
                    b.Navigation("ShopItems");
                });
#pragma warning restore 612, 618
        }
    }
}
